apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  selector:
    app: webapp
    release: "0-5"
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp-queue

spec:
  selector:
    app: webapp-fleetman-queue
    release: "1"
  ports:
    - name: tcp
      port: 8161
      nodePort: 30010
  type: NodePort
